Update dcr

diff --git a/docker_compose_alias/dcr b/docker_compose_alias/dcr
--- a/docker_compose_alias/dcr
+++ b/docker_compose_alias/dcr
@@ -3,4 +3,11 @@
 set -x
 
 SERVICES=$(docker compose config --services | grep $1)
+
+if [ -z "${SERVICES}" ]
+then
+    echo "service not found"
+    exit 1
+fi
+
 docker compose up -d --no-deps --force-recreate $SERVICES
